openapi: 3.0.0
info:
  description: "API Backend Dart"
  version: "1.0.10"
  title: "Semanda do Backend"
servers:
  - url: http://localhost:4466
    description: Local server
tags:
- name: "user"
  description: "Access to User"

paths:
  /user/{id}:
    get:
      tags:
        - 'user'
      summary: get user by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'success get user'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      
        '400':
          description: 'error connection'
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/BackendException'
    delete:
      tags:
        - 'user'
      summary: delete user by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'success delete user'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      
        '400':
          description: 'error connection'
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/BackendException'
  /user:
    get:
      tags:
        - 'user'
      summary: get all user
      responses:
        '200':
          description: 'success get users'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
      
        '400':
          description: 'error connection'
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/BackendException'
    post:
      tags:
        - 'user'
      summary: create new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        '200':
          description: 'success create user'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
      
        '400':
          description: 'error connection'
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/BackendException'
    put:
      tags:
        - 'user'
      summary: update user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: 'success update user'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
      
        '400':
          description: 'error connection'
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/BackendException'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        role:
          type: string
          default: user
          enum:
            - "dev"
            - "admin"
            - "manager"
    UserCreate:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string
          default: user
          enum:
            - "dev"
            - "admin"
            - "manager"
    BackendException:
      type: object
      properties:
        error:
          type: string